services:
  mysql-db:
    image: mysql:8.0
    container_name: [containerName]
#    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: [Enter your password]
      MYSQL_DATABASE: [startingDatabaseName]
    ports:
      - "3306:3306"
    volumes:
      - [pathTo:init.sql]:/docker-entrypoint-initdb.d/init.sql  #Maps init scripts to run on startup
      - [nameOfVault]:/var/lib/mysql #Connects the permanent vault, nameOfVault:/var/lib/mysql

volumes:
  [nameOfVault]:


